import type { Metadata } from "next";

import "./globals.css";
import Left from "@/components/left";
import Right from "@/components/right";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="px-2 flex sticky top-0 justify-between mx-auto max-w-screen-sm md:max-w-screen-md lg:max-w-screen-lg xl:max-w-screen-xl 2xl:max-w-screen-2xl  3xl:max-w-screen-3xl 4xl:max-w-screen-4xl  ">
          <div className="h-screen 3xl:pr-16  ">
            <Left />
          </div>
          <div className="flex-1 border-borderGray lg:min-w-[600px] border-x-1 ">
            {children}
          </div>
          <div className="flex-1 hidden lg:flex ">
            {" "}
            <Right />
          </div>
        </div>
      </body>
    </html>
  );
}
